// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// allocate_population_cpp
NumericVector allocate_population_cpp(NumericVector pop_total, IntegerVector cell_group, NumericVector volume, NumericVector area);
RcppExport SEXP _gloBFPr_allocate_population_cpp(SEXP pop_totalSEXP, SEXP cell_groupSEXP, SEXP volumeSEXP, SEXP areaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pop_total(pop_totalSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type cell_group(cell_groupSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type volume(volumeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type area(areaSEXP);
    rcpp_result_gen = Rcpp::wrap(allocate_population_cpp(pop_total, cell_group, volume, area));
    return rcpp_result_gen;
END_RCPP
}
// mean_pairwise_distance
double mean_pairwise_distance(Rcpp::NumericMatrix coords);
RcppExport SEXP _gloBFPr_mean_pairwise_distance(SEXP coordsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type coords(coordsSEXP);
    rcpp_result_gen = Rcpp::wrap(mean_pairwise_distance(coords));
    return rcpp_result_gen;
END_RCPP
}
// nearest_green_cpp
NumericVector nearest_green_cpp(NumericMatrix centroids, NumericMatrix green_xy, double radius);
RcppExport SEXP _gloBFPr_nearest_green_cpp(SEXP centroidsSEXP, SEXP green_xySEXP, SEXP radiusSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type centroids(centroidsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type green_xy(green_xySEXP);
    Rcpp::traits::input_parameter< double >::type radius(radiusSEXP);
    rcpp_result_gen = Rcpp::wrap(nearest_green_cpp(centroids, green_xy, radius));
    return rcpp_result_gen;
END_RCPP
}
// building_shadow_height_cpp
NumericVector building_shadow_height_cpp(NumericMatrix xy, List rings, IntegerVector ring_building, IntegerVector ring_part, LogicalVector ring_is_hole, NumericVector heights, double dx_unit, double dy_unit, double tan_elev);
RcppExport SEXP _gloBFPr_building_shadow_height_cpp(SEXP xySEXP, SEXP ringsSEXP, SEXP ring_buildingSEXP, SEXP ring_partSEXP, SEXP ring_is_holeSEXP, SEXP heightsSEXP, SEXP dx_unitSEXP, SEXP dy_unitSEXP, SEXP tan_elevSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type xy(xySEXP);
    Rcpp::traits::input_parameter< List >::type rings(ringsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ring_building(ring_buildingSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ring_part(ring_partSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type ring_is_hole(ring_is_holeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type heights(heightsSEXP);
    Rcpp::traits::input_parameter< double >::type dx_unit(dx_unitSEXP);
    Rcpp::traits::input_parameter< double >::type dy_unit(dy_unitSEXP);
    Rcpp::traits::input_parameter< double >::type tan_elev(tan_elevSEXP);
    rcpp_result_gen = Rcpp::wrap(building_shadow_height_cpp(xy, rings, ring_building, ring_part, ring_is_hole, heights, dx_unit, dy_unit, tan_elev));
    return rcpp_result_gen;
END_RCPP
}
// canopy_shadow_height_cpp
NumericVector canopy_shadow_height_cpp(NumericMatrix xy, NumericMatrix canopy_xy, NumericVector canopy_height, NumericVector canopy_ground, NumericVector target_ground, double dx_unit, double dy_unit, double tan_elev, double half_cell);
RcppExport SEXP _gloBFPr_canopy_shadow_height_cpp(SEXP xySEXP, SEXP canopy_xySEXP, SEXP canopy_heightSEXP, SEXP canopy_groundSEXP, SEXP target_groundSEXP, SEXP dx_unitSEXP, SEXP dy_unitSEXP, SEXP tan_elevSEXP, SEXP half_cellSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type xy(xySEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type canopy_xy(canopy_xySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type canopy_height(canopy_heightSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type canopy_ground(canopy_groundSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type target_ground(target_groundSEXP);
    Rcpp::traits::input_parameter< double >::type dx_unit(dx_unitSEXP);
    Rcpp::traits::input_parameter< double >::type dy_unit(dy_unitSEXP);
    Rcpp::traits::input_parameter< double >::type tan_elev(tan_elevSEXP);
    Rcpp::traits::input_parameter< double >::type half_cell(half_cellSEXP);
    rcpp_result_gen = Rcpp::wrap(canopy_shadow_height_cpp(xy, canopy_xy, canopy_height, canopy_ground, target_ground, dx_unit, dy_unit, tan_elev, half_cell));
    return rcpp_result_gen;
END_RCPP
}
// svf_cpp
NumericVector svf_cpp(NumericMatrix xy, NumericVector azimuth, List rings, IntegerVector ring_building, NumericVector building_height, NumericVector building_ground, NumericMatrix canopy_xy, NumericVector canopy_height, NumericVector canopy_ground, NumericVector observer_ground, NumericVector observer_height, double canopy_cell_size, double max_distance);
RcppExport SEXP _gloBFPr_svf_cpp(SEXP xySEXP, SEXP azimuthSEXP, SEXP ringsSEXP, SEXP ring_buildingSEXP, SEXP building_heightSEXP, SEXP building_groundSEXP, SEXP canopy_xySEXP, SEXP canopy_heightSEXP, SEXP canopy_groundSEXP, SEXP observer_groundSEXP, SEXP observer_heightSEXP, SEXP canopy_cell_sizeSEXP, SEXP max_distanceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type xy(xySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type azimuth(azimuthSEXP);
    Rcpp::traits::input_parameter< List >::type rings(ringsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ring_building(ring_buildingSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type building_height(building_heightSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type building_ground(building_groundSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type canopy_xy(canopy_xySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type canopy_height(canopy_heightSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type canopy_ground(canopy_groundSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type observer_ground(observer_groundSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type observer_height(observer_heightSEXP);
    Rcpp::traits::input_parameter< double >::type canopy_cell_size(canopy_cell_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type max_distance(max_distanceSEXP);
    rcpp_result_gen = Rcpp::wrap(svf_cpp(xy, azimuth, rings, ring_building, building_height, building_ground, canopy_xy, canopy_height, canopy_ground, observer_ground, observer_height, canopy_cell_size, max_distance));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_gloBFPr_allocate_population_cpp", (DL_FUNC) &_gloBFPr_allocate_population_cpp, 4},
    {"_gloBFPr_mean_pairwise_distance", (DL_FUNC) &_gloBFPr_mean_pairwise_distance, 1},
    {"_gloBFPr_nearest_green_cpp", (DL_FUNC) &_gloBFPr_nearest_green_cpp, 3},
    {"_gloBFPr_building_shadow_height_cpp", (DL_FUNC) &_gloBFPr_building_shadow_height_cpp, 9},
    {"_gloBFPr_canopy_shadow_height_cpp", (DL_FUNC) &_gloBFPr_canopy_shadow_height_cpp, 9},
    {"_gloBFPr_svf_cpp", (DL_FUNC) &_gloBFPr_svf_cpp, 13},
    {NULL, NULL, 0}
};

RcppExport void R_init_gloBFPr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
