#' @name get_metrics
#' @title get_metrics
#' @param x sf. building footprint polygon, typically output from [search_3dglobdf()]
#' @param quiet logical. If `TRUE`, suppress cli messages and progress bars.
#' @note
#' `x` must include a unique `id` field.
#' If `x` includes `group_id`, metrics that represent a whole building are
#' computed on temporary grouped features and copied back to the original rows.
#'
#' @references
#' Anna Labetski, Stelios Vitalis, Filip Biljecki, Ken Arroyo Ohori &
#' Jantien Stoter (2023): 3D building metrics for urban morphology.
#' International Journal of Geographical Information Science, 37(1):
#' 36-67. DOI: 10.1080/13658816.2022.2103818
#'
#' Rachid Hamaina, Thomas Leduc, Guillaume Moreau.
#' Towards Urban Fabrics Characterization Based on Buildings Footprints.
#' Jerome Gensel; Didier Josselin; Danny Vandenbroucke.
#' Bridging the Geographic Information Sciences- International AGILE'2012 Conference,
#' Avignon (France), April, 24-27, 2012, Springer Berlin Heidelberg,
#' pp.327-346, 2012, 978-3-642-29062-6. 10.1007/978-3-642-290633_18. hal-01347299
#'
#' Melchiorri, M., Freire, S., Schiavina, M. et al.
#' The Multi-temporal and Multi-dimensional Global Urban Centre Database to
#' Delineate and Analyse World Cities. Sci Data 11, 82 (2024).
#' https://doi.org/10.1038/s41597-023-02691-1
#'
#' Essential background in Pesaresi, M. et al. (2024) "Advances on the Global Human
#' Settlement Layer by joint assessment of Earth Observation and population survey data",
#' International Journal of Digital Earth, 17(1).
#'
#' @importFrom terra as.points viewshed cellSize ifel terraOptions
#' @importFrom sf st_as_sf st_nearest_feature st_distance st_centroid st_coordinates st_area st_perimeter
#' @importFrom sf st_minimum_rotated_rectangle
#' @importFrom terra merge
#' @importFrom future plan multisession sequential multicore availableCores
#' @importFrom furrr future_map furrr_options
#' @importFrom parallelly supportsMulticore
#' @importFrom utils txtProgressBar setTxtProgressBar


#' @description
#' `get_morphology`: Computes a set of morphological properties and geometric descriptors for each building footprint polygon.
#' These include area, perimeter, surface area, volume, shape compactness, elongation, and accessibility measures.
#' If `x` contains a `group_id` column, features with the same `group_id` are
#' treated as one building for morphology metrics while the returned rows and
#' geometries remain unchanged.
#' @param metrics vector. A list of metrics to be computed. All metrics will be computed by default.
#' @return
#' `get_morphology` returns an `sf` object identical to input \code{x},
#' with additional columns for:
#' \itemize{
#'  \item \code{g_area}: Ground area of footprint
#'  \item \code{pmeter}: Perimeter length of footprint
#'  \item \code{v_surf}: Vertical surface area (walls)
#'  \item \code{t_surf}: Total surface area (walls + roof)
#'  \item \code{vol}: Volume (area * height)
#'  \item \code{obb_vol}: Volume of oriented bounding box
#'  \item \code{pa_ratio}: Perimeter-area ratio
#'  \item \code{rec}: Rectangular compactness
#'  \item \code{fra}: Fractal dimension ratio
#'  \item \code{cbn}: Cuboidness index
#'  \item \code{hem}: Hemisphericality index
#'  \item \code{cnv}: Convexity index
#'  \item \code{me_dist}: Mean edge accessibility distance
#'  \item \code{mp_dist}: Mean pairwise distance within the footprint
#'  \item \code{vol_exch}: Volume exchange ratio
#'  \item \code{elo_x/elo_y/elo_z}: Elongation ratios (x/y/z axis)
#' }
#'
#' @examples
#' library(gloBFPr)
#' data(globfp_example)
#' result <- gloBFPr::get_morphology(globfp_example[c(1:3),], quiet = TRUE)
#'
#' @export
#' @rdname get_metrics
get_morphology <- function(x = NULL,
                           metrics = c('g_area', 'pmeter', 'v_surf', 't_surf',
                                       'vol', 'obb_vol', 'pa_ratio', 'rec',
                                       'fra', 'cbn', 'hem', 'cnv',
                                       'me_dist', 'mp_dist', 'vol_exch', 'elo_x',
                                       'elo_y', 'elo_z'),
                           quiet = FALSE) {
  if (inherits(x, 'NULL')) {
    if (!quiet) cli::cli_alert_info("Please input building footprint polygon generated by `search_3dglobdf()`.")
    return(x)
  }
  projected_poly <- x

  old_opt <- getOption("future.globals.maxSize")
  on.exit(options(future.globals.maxSize = old_opt), add = TRUE)
  options(future.globals.maxSize = 3 * 1024^3)

  workers <- max(1, as.numeric(future::availableCores()) - 1)
  # Set future plan depending on OS
  os <- Sys.info()[["sysname"]]
  if (workers == 1) {
    future::plan(future::sequential)
  } else if (os == "Windows" || isFALSE(parallelly::supportsMulticore())) {
    future::plan(future::multisession, workers = workers)
  } else {
    future::plan(future::multicore, workers = workers)
  }
  on.exit(future::plan(future::sequential), add = TRUE)

  start_time <- Sys.time()
  requested_metrics <- unique(metrics)
  analysis_poly <- prepare_morphology_units(projected_poly)
  group_metrics <- "group_id" %in% names(projected_poly)
  property_metrics <- c("g_area", "pmeter", "v_surf", "t_surf", "vol", "obb_vol")
  required_properties <- intersect(property_metrics, requested_metrics)
  if (any(c("pa_ratio", "rec", "cnv", "hem", "fra") %in% requested_metrics)) {
    required_properties <- c(required_properties, "g_area")
  }
  if (any(c("pa_ratio", "fra") %in% requested_metrics)) {
    required_properties <- c(required_properties, "pmeter")
  }
  if (any(c("cbn", "hem", "vol_exch") %in% requested_metrics)) {
    required_properties <- c(required_properties, "vol")
  }
  if ("cbn" %in% requested_metrics) {
    required_properties <- c(required_properties, "obb_vol")
  }
  required_properties <- unique(required_properties)

  #--- Properties ---
  if (!quiet) cli::cli_alert_info('Start computing geometric properties ...')
  if ("g_area" %in% required_properties) analysis_poly$g_area <- get_morphology_property(analysis_poly, "g_area")
  if ("pmeter" %in% required_properties) analysis_poly$pmeter <- get_morphology_property(analysis_poly, "pmeter")
  if ("v_surf" %in% required_properties) analysis_poly$v_surf <- get_morphology_property(analysis_poly, "v_surf")
  if ("t_surf" %in% required_properties) analysis_poly$t_surf <- get_morphology_property(analysis_poly, "t_surf")
  if ("vol" %in% required_properties) analysis_poly$vol <- get_morphology_property(analysis_poly, "vol")
  if ("obb_vol" %in% required_properties) analysis_poly$obb_vol <- get_morphology_property(analysis_poly, "obb_vol")

  #--- Indices ---
  if (!quiet) cli::cli_alert_info('Parallel computing for geometric indices ...')
  if ("pa_ratio" %in% metrics) analysis_poly$pa_ratio <- analysis_poly$pmeter / analysis_poly$g_area # Perimeter-Area Ratio
  if ("rec" %in% metrics) analysis_poly$rec <- as.numeric(analysis_poly$g_area / sf::st_area(sf::st_minimum_rotated_rectangle(analysis_poly)))
  if ("fra" %in% metrics) analysis_poly$fra <- 2 * log(as.numeric(analysis_poly$pmeter)) / log(as.numeric(analysis_poly$g_area))
  if ("cbn" %in% metrics) analysis_poly$cbn <- as.numeric(analysis_poly$vol) / as.numeric(analysis_poly$obb_vol)

  # --- Parallel Loop for Shape Metrics ---
  building_list <- lapply(seq_len(nrow(analysis_poly)), function(i) analysis_poly[i, ])
  morpho_results <- furrr::future_map(
    building_list,
    function(poly_) {
      m <- list()
      if ("hem" %in% metrics) m$hem <- cal_hemisphericality(poly_)
      if ("cnv" %in% metrics) m$cnv <- cal_convexity(poly_)
      group_parts <- if (".group_parts" %in% names(poly_)) poly_$.group_parts[[1]] else NULL
      if ("me_dist" %in% metrics) {
        m$me_dist <- if (is.null(group_parts)) cal_accessibility(poly_) else cal_accessibility_group(group_parts)
      }
      if ("mp_dist" %in% metrics) {
        m$mp_dist <- if (is.null(group_parts)) cal_mean_pairwise_distance(poly_) else cal_mean_pairwise_distance_group(group_parts)
      }
      if ("vol_exch" %in% metrics) m$vol_exch <- cal_volume_exchange_ratio(poly_)
      if ("elo_x" %in% metrics | "elo_y" %in% metrics | "elo_z" %in% metrics) {
        m$elo_ratios <- cal_elongation_ratios(poly_)
      }
      return(m)
    },
    .options = furrr::furrr_options(seed = TRUE),
    .progress = !quiet
  )

  # --- Assign results back ---
  get_metric_value <- function(result, name) {
    value <- result[[name]]
    if (is.null(value) || length(value) != 1 || is.na(value)) return(NA_real_)
    as.numeric(value)
  }
  get_elo_value <- function(result, index) {
    value <- result$elo_ratios
    if (is.null(value) || length(value) < index || length(value[[index]]) != 1) return(NA_real_)
    as.numeric(value[[index]])
  }

  if ("hem" %in% metrics) analysis_poly$hem <- vapply(morpho_results, get_metric_value, numeric(1), name = "hem")
  if ("cnv" %in% metrics) analysis_poly$cnv <- vapply(morpho_results, get_metric_value, numeric(1), name = "cnv")
  if ("me_dist" %in% metrics) analysis_poly$me_dist <- vapply(morpho_results, get_metric_value, numeric(1), name = "me_dist")
  if ("mp_dist" %in% metrics) analysis_poly$mp_dist <- vapply(morpho_results, get_metric_value, numeric(1), name = "mp_dist")
  if ("vol_exch" %in% metrics) analysis_poly$vol_exch <- vapply(morpho_results, get_metric_value, numeric(1), name = "vol_exch")
  if ("elo_x" %in% metrics) analysis_poly$elo_x <- vapply(morpho_results, get_elo_value, numeric(1), index = 1)
  if ("elo_y" %in% metrics) analysis_poly$elo_y <- vapply(morpho_results, get_elo_value, numeric(1), index = 2)
  if ("elo_z" %in% metrics) analysis_poly$elo_z <- vapply(morpho_results, get_elo_value, numeric(1), index = 3)

  metric_cols <- intersect(
    requested_metrics,
    names(analysis_poly)
  )
  if (group_metrics) {
    match_idx <- match(projected_poly$group_id, analysis_poly$group_id)
    for (col in metric_cols) {
      projected_poly[[col]] <- analysis_poly[[col]][match_idx]
    }
  } else {
    for (col in metric_cols) {
      projected_poly[[col]] <- analysis_poly[[col]]
    }
  }

  if (!quiet) cli::cli_alert_success('Finished computing morphology metrics')

  end_time <- Sys.time()
  process_time <- as.numeric(difftime(end_time, start_time, units = "secs"))
  if (!quiet) time_taken(process_time)

  return(projected_poly)
}

#' @noRd
get_pop <- function(x = NULL, year = 2025, quiet = FALSE) {
  if (inherits(x, 'NULL')) {
    if (!quiet) cli::cli_alert_info("Please input building footprint polygon generated by `search_3dglobdf()`.")
    return(x)
  }

  old_terra_progress <- terra::terraOptions(print = FALSE)$progress
  terra::terraOptions(progress = 0)
  on.exit(terra::terraOptions(progress = old_terra_progress), add = TRUE)

  start_time <- Sys.time()

  input_bbox <- get_bbox(x)
  utm_crs <- get_utm_crs(input_bbox)
  projected_poly <- sf::st_transform(x, utm_crs)
  analysis_poly <- prepare_morphology_units(projected_poly)

  centroids <- suppressWarnings(sf::st_centroid(analysis_poly))
  pop <- get_GHSpop(bbox = input_bbox, year = year, points = centroids, quiet = quiet)

  volumes <- get_morphology_property(analysis_poly, "vol")
  footprint_areas <- as.numeric(sf::st_area(analysis_poly))
  cell_group <- match(pop$cell_id, unique(stats::na.omit(pop$cell_id)))
  allocated_pop <- allocate_population_cpp(
    pop_total = pop$pop_total,
    cell_group = cell_group,
    volume = volumes,
    area = footprint_areas
  )

  analysis_poly$pop_total <- allocated_pop
  projected_poly <- copy_group_results(projected_poly, analysis_poly, "pop_total")

  if (!quiet) cli::cli_alert_success('Finished linking (GHSL) population to buildings')
  end_time <- Sys.time()
  process_time <- as.numeric(difftime(end_time, start_time, units = "secs"))
  if (!quiet) time_taken(process_time)

  return(projected_poly)
}

#' Estimate residential and non-residential buildings from GHSL built-up surface
#'
#' INTERNAL AND UNSTABLE. Not exported: the classification is still under
#' development and its interface and output columns are expected to change.
#' See `dev/design-get_residential-overture-poi.md` for the planned revision.
#' Do not add an `@export` tag or call this from an exported function without
#' first revisiting that design note.
#'
#' @param x sf. Building footprint polygons from `search_3dglobdf()`.
#' @param year integer. GHS built-up surface year. Required.
#' @param threshold numeric. Threshold (%) for deciding whether a building is
#'   residential. With `threshold = 70`, a building in a cell whose residential
#'   share of built-up surface exceeds 70% is classified as residential.
#' @param quiet logical. Suppress cli messages.
#'
#' @return An `sf` object identical to `x` with additional columns:
#'   `res` (logical, residential or not), `res_pct` (residential built-up
#'   surface percentage in the matched GHSL cell), and `total_built_vals`,
#'   `nres_vals`, `res_vals` (extracted total, non-residential and residential
#'   built-up surface values from the matched cell).
#'
#' @noRd
get_residential <- function(x = NULL, year = NULL, threshold = 80, quiet = FALSE) {
  if (inherits(x, 'NULL')) {
    if (!quiet) cli::cli_alert_info("Please input building footprint polygon generated by `search_3dglobdf()`.")
    return(NULL)
  }

  if (inherits(year, 'NULL')) {
    if (!quiet) cli::cli_alert_info("Please input year")
    return(NULL)
  }

  old_terra_progress <- terra::terraOptions(print = FALSE)$progress
  terra::terraOptions(progress = 0)
  on.exit(terra::terraOptions(progress = old_terra_progress), add = TRUE)

  start_time <- Sys.time()

  bbox <- get_bbox(x)
  utm_crs <- get_utm_crs(bbox)
  projected_poly <- sf::st_transform(x, utm_crs)
  analysis_poly <- prepare_group_analysis_buildings(projected_poly)
  analysis_poly$res <- FALSE
  analysis_poly$g_area <- as.numeric(sf::st_area(analysis_poly$geometry))

  # calculate residential
  ghs <- get_GHSres(bbox = bbox, year = year)
  if (!all(c("total", "nres", "res") %in% names(ghs))) {
    stop("`get_GHSres()` must return total, nres, and res rasters.")
  }

  # use all centroids of projected_poly to extract value from rasters
  centroids <- terra::vect(suppressWarnings(sf::st_centroid(analysis_poly)))
  total_vals <- suppressWarnings(
    terra::extract(ghs$total, centroids, raw = TRUE, ID = FALSE)[, 1]
  )
  nres_vals <- suppressWarnings(
    terra::extract(ghs$nres, centroids, raw = TRUE, ID = FALSE)[, 1]
  )
  res_vals <- suppressWarnings(
    terra::extract(ghs$res, centroids, raw = TRUE, ID = FALSE)[, 1]
  )

  # link building surface area back to projected_poly
  analysis_poly$total_built_vals <- total_vals
  analysis_poly$nres_vals <- nres_vals
  analysis_poly$res_vals <- res_vals
  analysis_poly$res_pct <- ifelse(
    !is.na(total_vals) & total_vals > 0,
    100 * res_vals / total_vals,
    NA_real_
  )

  # classify residential building
  analysis_poly$res <- !is.na(analysis_poly$res_pct) &
    analysis_poly$total_built_vals > 0 &
    analysis_poly$res_pct >= threshold
  projected_poly <- copy_group_results(
    projected_poly,
    analysis_poly,
    c("g_area", "total_built_vals", "nres_vals", "res_vals", "res_pct", "res")
  )

  if (!quiet) cli::cli_alert_success('Finished estimating residential buildings')
  end_time <- Sys.time()
  process_time <- as.numeric(difftime(end_time, start_time, units = "secs"))
  if (!quiet) time_taken(process_time)

  return(projected_poly)
}

#' @description
#' `get_neighbors`: Computes the number of neighboring buildings and centroid
#' distance summaries, based on a fixed-radius buffer and
#' Voronoi-based adjacency.
#'
#' @param radius numeric. (only required for `get_neighbors`, `get_gbvi`, and
#' `get_dng`)
#' A numeric value specifying the buffer radius (in meters) used to define
#' the proximity of a building footprint centroid. Default for `get_neighbors`, and
#' `get_gbvi` and `get_dng` is respectfully 500 and 800.
#'
#' @return
#' `get_neighbors` returns an `sf` object identical to input \code{x},
#' with additional columns for:
#' \itemize{
#'   \item \code{n_count}: Number of adjacent buildings within the radius.
#'   \item \code{m_ndist}: Mean distance from the building centroid
#'   to neighboring building centroids.
#'   \item \code{min_ndist}: Minimum distance to neighboring building centroids.
#'   \item \code{max_ndist}: Maximum distance to neighboring building centroids.
#'   \item \code{sd_ndist}: Standard deviation of those distances.
#' }
#'
#'
#' @examples
#' result <- gloBFPr::get_neighbors(globfp_example[c(1:3),], radius = 100)
#' @importFrom Rcpp evalCpp
#' @export
#' @rdname get_metrics
get_neighbors <- function(x = NULL, radius = 500, quiet = FALSE) {
  if (inherits(x, 'NULL')) {
    if (!quiet) cli::cli_alert_info("Please input building footprint polygon generated by `search_3dglobdf()`.")
    return(x)
  }

  old_opt <- getOption("future.globals.maxSize")
  on.exit(options(future.globals.maxSize = old_opt), add = TRUE)
  options(future.globals.maxSize = 3 * 1024^3)

  workers <- max(1, as.numeric(future::availableCores()) - 1)
  # Set future plan depending on OS
  os <- Sys.info()[["sysname"]]
  if (workers == 1) {
    future::plan(future::sequential)
  } else if (os == "Windows" || isFALSE(parallelly::supportsMulticore())) {
    future::plan(future::multisession, workers = workers)
  } else {
    future::plan(future::multicore, workers = workers)
  }
  on.exit(future::plan(future::sequential), add = TRUE)

  start_time <- Sys.time()
  utm_crs <- get_utm_crs(get_bbox(x))
  projected_poly <- sf::st_transform(x, utm_crs)
  analysis_poly <- prepare_group_analysis_buildings(projected_poly)

  # Ensure consistent IDs
  if (!"id" %in% names(analysis_poly)) {
    analysis_poly$id <- seq_len(nrow(analysis_poly))
  }

  # Precompute centroids once
  all_centroids <- suppressWarnings(sf::st_centroid(analysis_poly))

  # Prepare a list of per-building input objects
  if (!quiet) pb <- utils::txtProgressBar(min = 0, max = nrow(analysis_poly), style = 3)
  input_list <- lapply(seq_len(nrow(analysis_poly)), function(i) {
    if (!quiet) utils::setTxtProgressBar(pb, i)
    list(
      poly = analysis_poly[i, ],
      poly_id = analysis_poly$id[i],
      all_polys = analysis_poly,
      all_centroids = all_centroids,
      radius = radius
    )
  })
  if (!quiet) close(pb)

  # Parallel computation
  neighbor_results <- furrr::future_map(
    input_list,
    function(b) {
      poly_ <- b$poly
      poly_id <- b$poly_id
      all_polys <- b$all_polys
      all_centroids <- b$all_centroids
      radius <- b$radius

      # Get centroid and buffer
      this_centroid <- suppressWarnings(sf::st_centroid(poly_))
      buffer_zone <- sf::st_buffer(this_centroid, dist = radius)
      buffer_zone <- sf::st_transform(buffer_zone, sf::st_crs(all_polys))

      # Filter neighbors within buffer
      intersected <- sf::st_intersects(all_polys, buffer_zone, sparse = FALSE)[, 1]
      if (sum(intersected) <= 1) {
        return(list(n = 0, m = NA_real_, min = NA_real_, max = NA_real_, sd = NA_real_))
      }

      filtered_poly <- all_polys[intersected, ]
      filtered_centroids <- all_centroids[intersected, ]
      centroid_union <- sf::st_union(filtered_centroids)
      voronoi_polygons <- sf::st_voronoi(centroid_union) |>
        sf::st_collection_extract("POLYGON")
      voronoi_sf <- sf::st_sf(geometry = sf::st_sfc(voronoi_polygons),
                              crs = sf::st_crs(filtered_poly))
      voronoi_sf$id <- seq_len(nrow(filtered_poly))

      # Index of current building in filtered set
      idx <- which(filtered_poly$id == poly_id)
      if (length(idx) == 0) {
        return(list(n = 0, m = NA_real_, min = NA_real_, max = NA_real_, sd = NA_real_))
      }

      # Find touching polygons
      adjacency <- sf::st_touches(voronoi_sf)
      neighbor_ids <- adjacency[[idx]]
      if (length(neighbor_ids) == 0) {
        return(list(n = 0, m = NA_real_, min = NA_real_, max = NA_real_, sd = NA_real_))
      }

      neighbor_centroids <- filtered_centroids[neighbor_ids, ]
      dists <- sf::st_distance(this_centroid, neighbor_centroids)
      dist_values <- as.numeric(dists)
      mean_dist <- mean(dist_values)
      min_dist <- min(dist_values)
      max_dist <- max(dist_values)
      sd_dist <- if (length(dist_values) > 1) stats::sd(dist_values) else NA_real_

      return(list(n = length(neighbor_ids), m = mean_dist, min = min_dist, max = max_dist, sd = sd_dist))
    },
    .options = furrr::furrr_options(seed = TRUE),
    .progress = !quiet
  )

  # Combine results back into the main data
  analysis_poly$n_count <- vapply(neighbor_results, function(x) x$n, numeric(1))
  analysis_poly$m_ndist <- vapply(neighbor_results, function(x) x$m, numeric(1))
  analysis_poly$min_ndist <- vapply(neighbor_results, function(x) x$min, numeric(1))
  analysis_poly$max_ndist <- vapply(neighbor_results, function(x) x$max, numeric(1))
  analysis_poly$sd_ndist <- vapply(neighbor_results, function(x) x$sd, numeric(1))
  projected_poly <- copy_group_results(
    projected_poly,
    analysis_poly,
    c("n_count", "m_ndist", "min_ndist", "max_ndist", "sd_ndist")
  )

  end_time <- Sys.time()
  process_time <- as.numeric(difftime(end_time, start_time, units = "secs"))
  if (!quiet) time_taken(process_time)

  return(projected_poly)
}


#' @description
#' `get_bgvi`: Calculate the Building Green View Index (BGVI) for each building volume.
#' Neighboring buildings in the internal DSM used for the viewshed are given a
#' single flat roof elevation (base ground elevation at their centroid, plus
#' height) rather than following the terrain slope pixel by pixel, matching
#' [get_fused_dsm()].
#' @param datasource_canopy_height character or `NULL`. Canopy height source for
#' building the DSM and canopy green feature layer. Currently supports
#' \code{"metachm"}, \code{"ethCHM"}, or `NULL`. If `NULL`, the DSM is built
#' from buildings and DEM only.
#' @param datasource_greenspace character or `NULL`. Optional 2D greenspace map
#' tile source for the visible-green feature layer. Supports \code{"esri"} and
#' \code{"sentinel2"}. If both canopy height and greenspace sources are supplied,
#' the visible-green layer is the union of height-filtered canopy and 2D
#' greenspace.
#' @param min_tree_height numeric. (only required for `get_bgvi` and `get_dng`)
#' When `datasource_canopy_height` is a canopy height source, minimum height threshold (in
#' meters) to classify vegetation as trees in the CHM. Default is 2.
#' @param zoom numeric. (only required for `get_bgvi` and `get_dng`)
#' Zoom level of map tile when `datasource_greenspace = "esri"` or
#' `datasource_greenspace = "sentinel2"`.
#' The default is `17`. The higher level of zoom will lead to higher resolution
#' of greenspace data for computing BGVI or DNG.
#' @param year numeric. The desired year for Sentinel-2 cloudless mosaic
#' tiles. (This has to be specified when `datasource_greenspace = "sentinel2"`)
#' @param floor logical. (only required for `get_bgvi`)
#' Whether to compute Building Green View Index (BGVI) for each floor level
#' based on estimated number of floors. Default is `FALSE`.
#' @param floor_step integer. (only required for `get_bgvi` when
#' \code{floor = TRUE}) Compute GVI every \code{floor_step} floors. The top
#' estimated floor is always included. Default is \code{1}, meaning every floor.
#' @param short_building_threshold numeric. (only required for `get_bgvi`)
#' Height threshold in meters for deciding whether a building should use only
#' the bottom viewpoint in non-floor mode. Default is 6.
#' @param field_of_view numeric. (only required for directional `get_bgvi`)
#' Angular field of view in degrees for direction-specific GVI. Used only when
#' `directions` is not `NULL`. Default is 45.
#' @param directions character vector or `NULL`. Optional direction names for
#' direction-specific GVI. Valid values are \code{"southwest"},
#' \code{"southeast"}, \code{"northeast"}, \code{"northwest"}, \code{"north"},
#' \code{"east"}, \code{"west"}, and \code{"south"}. If `NULL`,
#' `field_of_view` is ignored and only non-directional GVI columns are returned.
#' @param workers integer. (only required for `get_bgvi`) Number of parallel
#' workers. Defaults to one fewer than available cores, capped at 4. Use
#' \code{workers = 1} to run sequentially and reduce memory pressure.
#' @param resolution numeric or `NULL`. (only used by `get_bgvi`) Output
#' raster resolution in meters for the internal DSM used for viewshed
#' computation. If `NULL` (default), the finest native resolution among the
#' downloaded DEM and canopy height model is used, matching
#' [get_fused_dsm()]. Set explicitly (e.g. `1`) to force a finer grid.
#' @param key character. (only required for `get_bgvi`)
#' API key of OpenTopography.
#'
#' @details
#' When `floor = TRUE`, `get_bgvi()` estimates the number of floors from
#' building height and computes GVI from selected floor viewpoints. The
#' `floor_step` argument controls how densely floors are sampled. If
#' `floor_step = 1`, GVI is computed for every estimated floor. If
#' `floor_step > 1`, GVI is computed every `floor_step` floors to reduce
#' runtime; for example, `floor_step = 3` samples floors 1, 4, 7, and so on.
#' The top estimated floor is always included, even when it does not fall on
#' the step sequence.
#'
#' If `directions` is provided, `get_bgvi()` also computes direction-specific
#' GVI by applying the requested `field_of_view` around each direction within
#' each computed viewshed. The viewshed itself is computed once per viewpoint,
#' then reused for each direction. Direction-specific columns are named with the
#' direction suffix, such as \code{gvi_bottom_south}, \code{gvi_top_south},
#' \code{mean_gvi_south}, \code{min_gvi_south}, \code{max_gvi_south}, and
#' \code{sd_gvi_south}.
#'
#' @return
#' `get_bgvi` returns an `sf` object identical to input \code{x},
#' with additional columns for:
#' \itemize{
#'   \item \code{mean_gvi}: Mean Building Green View Index value (0 to 1) from selected height(s).
#'   \item \code{bottom_gvi}: Building Green View Index from the bottom
#'   viewpoint, 1.7 m above ground.
#'   \item \code{top_gvi}: Building Green View Index from the top viewpoint.
#'   For short buildings, this is equal to \code{bottom_gvi}.
#'   \item \code{bottom_green_area}: Visible green area (m\eqn{^2}) from the bottom viewpoint.
#'   \item \code{top_green_area}: Visible green area (m\eqn{^2}) from the top viewpoint.
#'   \item \code{mean_green_area}: Mean visible green area (m\eqn{^2}) across viewpoints.
#'   \item \code{min_gvi}, \code{max_gvi}, \code{sd_gvi}: Minimum, maximum,
#'   and standard deviation of Green View Index (GVI) (if \code{floor = TRUE}).
#'   \item \code{estimated_floors}: Estimated number of floors based on building height
#'   (if \code{floor = TRUE}).
#'}
#'
#' @note
#' To request an OpenTopography API token, please visit:
#' [https://portal.opentopography.org/requestService?service=api](https://portal.opentopography.org/requestService?service=api)
#'
#' USGS 3DEP 1m/10m raster dataset is currently restricted to academic users.
#' Academic users can request access to these data via the OpenTopography portal.
#' Non-academic users can enquire about an enterprise API key by emailing info@opentopography.org.
#' See OpenTopography Terms of Use for more information on appropriate use of the API.
#'
#'
#' @examples
#' \donttest{
#' result <- gloBFPr::get_bgvi(globfp_example[c(1:3),],
#'                             datasource_canopy_height = "metachm",
#'                             datasource_greenspace = "esri",
#'                             key = "YOUR_opentopography_API_KEY")
#' }
#'
#' @references
#' Qi, L., Hu, Y., Bu, R., Xiong, Z., Li, B., Zhang, C., ... & Li, C. (2024).
#' Spatial-temporal patterns and influencing factors of the Building Green View
#' Index: A new approach for quantifying 3D urban greenery visibility.
#' Sustainable Cities and Society, 111, 105518.
#'
#' @export
#' @rdname get_metrics

get_bgvi <- function(x = NULL,
                     datasource_canopy_height = "metachm",
                     datasource_greenspace = NULL,
                     min_tree_height = 2,
                     zoom = 17,
                     radius = 800,
                     year = NULL,
                     floor = FALSE,
                     floor_step = 3,
                     short_building_threshold = 6,
                     field_of_view = 45,
                     directions = NULL,
                     workers = NULL,
                     resolution = NULL,
                     key = NULL,
                     quiet = FALSE) {
  if (inherits(x, 'NULL')) {
    if (!quiet) cli::cli_alert_info("Please input building footprint polygon generated by `search_3dglobdf()`.")
    return(x)
  }
  if (inherits(key, 'NULL')) {
    stop("API key for OpenTopography is missing.")
  }

  # Store the original 'timeout' option and ensure it's reset upon function exit
  original_timeout <- getOption('timeout')
  on.exit(options(timeout = original_timeout), add = TRUE)
  options(timeout=9999)

  old_opt <- getOption("future.globals.maxSize")
  on.exit(options(future.globals.maxSize = old_opt), add = TRUE)
  options(future.globals.maxSize = 3 * 1024^3)

  old_terra_progress <- terra::terraOptions(print = FALSE)$progress
  terra::terraOptions(progress = 0)
  on.exit(terra::terraOptions(progress = old_terra_progress), add = TRUE)

  floor_step <- as.integer(floor_step[1])
  if (is.na(floor_step) || floor_step < 1L) floor_step <- 1L
  short_building_threshold <- as.numeric(short_building_threshold[1])
  if (is.na(short_building_threshold) || short_building_threshold <= 0) {
    stop("`short_building_threshold` must be a positive numeric value in meters.", call. = FALSE)
  }
  if (!inherits(directions, "NULL")) {
    directions <- validate_bgvi_directions(directions)
    field_of_view <- validate_bgvi_field_of_view(field_of_view)
  } else {
    field_of_view <- NULL
  }

  if (inherits(workers, "NULL")) {
    workers <- min(max(1, as.numeric(future::availableCores()) - 1), 4)
  } else {
    workers <- as.integer(workers[1])
    if (is.na(workers) || workers < 1L) workers <- 1L
  }
  # Set future plan depending on OS
  os <- Sys.info()[["sysname"]]
  if (workers == 1) {
    future::plan(future::sequential)
  } else if (os == "Windows" || isFALSE(parallelly::supportsMulticore())) {
    future::plan(future::multisession, workers = workers)
  } else {
    future::plan(future::multicore, workers = workers)
  }
  on.exit(future::plan(future::sequential), add = TRUE)

  start_time <- Sys.time()

  bgvi_inputs <- prepare_bgvi_inputs(
    x = x,
    datasource_canopy_height = datasource_canopy_height,
    datasource_greenspace = datasource_greenspace,
    min_tree_height = min_tree_height,
    zoom = zoom,
    radius = radius,
    year = year,
    resolution = resolution,
    key = key,
    quiet = quiet
  )
  projected_poly <- bgvi_inputs$projected_poly
  analysis_poly <- bgvi_inputs$analysis_poly

  if (isTRUE(floor)) {
    analysis_poly$estimated_floors <- round(analysis_poly$Height / 3)
    analysis_poly$estimated_floors <- base::ifelse(
      analysis_poly$g_area < 30 | analysis_poly$Height < short_building_threshold,
      1,
      analysis_poly$estimated_floors
    )
    analysis_poly$min_gvi <- 0
    analysis_poly$max_gvi <- 0
    analysis_poly$sd_gvi  <- 0
  }
  analysis_poly$mean_gvi <- 0
  analysis_poly$bottom_gvi <- 0
  analysis_poly$top_gvi <- 0

  # --- Parallel Processing ---
  # cli::cli_alert_info('Preparing parallel processing ...')
  if (!quiet) pb <- utils::txtProgressBar(min = 0, max = nrow(analysis_poly), style = 3)
  building_list <- lapply(seq_len(nrow(analysis_poly)), function(i) {
    if (!quiet) utils::setTxtProgressBar(pb, i)
    list(
      building = analysis_poly[i, ]
    )
  })
  if (!quiet) close(pb)

  # Save raster layers to disk to avoid pointer serialization issues
  dem_path <- tempfile(fileext = ".tif")
  chm_path <- tempfile(fileext = ".tif")
  binary_green_path <- tempfile(fileext = ".tif")
  bh_all_path <- tempfile(fileext = ".tif")
  base_elev_path <- tempfile(fileext = ".tif")
  bldg_id_path <- tempfile(fileext = ".tif")
  terra::writeRaster(bgvi_inputs$dem, dem_path, overwrite = TRUE)
  terra::writeRaster(bgvi_inputs$chm, chm_path, overwrite = TRUE)
  terra::writeRaster(bgvi_inputs$binary_green, binary_green_path, overwrite = TRUE)
  terra::writeRaster(bgvi_inputs$bh_all, bh_all_path, overwrite = TRUE)
  terra::writeRaster(bgvi_inputs$base_elev, base_elev_path, overwrite = TRUE)
  terra::writeRaster(bgvi_inputs$bldg_id, bldg_id_path, overwrite = TRUE)
  on.exit(unlink(c(dem_path, chm_path, binary_green_path, bh_all_path,
                   base_elev_path, bldg_id_path)), add = TRUE)

  gvi_results <- furrr::future_map(
    building_list,
    function(b) compute_gvi_per_building(
      building = b$building,
      dem_path = dem_path,
      chm_path = chm_path,
      binary_green_path = binary_green_path,
      bh_all_path = bh_all_path,
      base_elev_path = base_elev_path,
      bldg_id_path = bldg_id_path,
      radius = radius,
      floor = floor,
      floor_step = floor_step,
      short_building_threshold = short_building_threshold,
      directions = directions,
      field_of_view = field_of_view
    ),
    .options = furrr::furrr_options(seed = TRUE),
    .progress = !quiet
  )

  analysis_poly$mean_gvi <- vapply(gvi_results, function(x) x$mean, numeric(1))
  analysis_poly$bottom_gvi <- vapply(gvi_results, function(x) x$bottom, numeric(1))
  analysis_poly$top_gvi <- vapply(gvi_results, function(x) x$top, numeric(1))
  analysis_poly$bottom_green_area <- vapply(gvi_results, function(x) x$bottom_green_area, numeric(1))
  analysis_poly$top_green_area    <- vapply(gvi_results, function(x) x$top_green_area, numeric(1))
  analysis_poly$mean_green_area   <- vapply(gvi_results, function(x) x$mean_green_area, numeric(1))
  if (isTRUE(floor)) {
    analysis_poly$min_gvi <- vapply(gvi_results, function(x) x$min, numeric(1))
    analysis_poly$max_gvi <- vapply(gvi_results, function(x) x$max, numeric(1))
    analysis_poly$sd_gvi  <- vapply(gvi_results, function(x) x$sd, numeric(1))
  }
  if (!inherits(directions, "NULL")) {
    for (direction in directions) {
      analysis_poly[[paste0("gvi_bottom_", direction)]] <- vapply(
        gvi_results,
        function(x) x$directions[[direction]]$bottom,
        numeric(1)
      )
      analysis_poly[[paste0("gvi_top_", direction)]] <- vapply(
        gvi_results,
        function(x) x$directions[[direction]]$top,
        numeric(1)
      )
      analysis_poly[[paste0("mean_gvi_", direction)]] <- vapply(
        gvi_results,
        function(x) x$directions[[direction]]$mean,
        numeric(1)
      )
      analysis_poly[[paste0("min_gvi_", direction)]] <- vapply(
        gvi_results,
        function(x) x$directions[[direction]]$min,
        numeric(1)
      )
      analysis_poly[[paste0("max_gvi_", direction)]] <- vapply(
        gvi_results,
        function(x) x$directions[[direction]]$max,
        numeric(1)
      )
      analysis_poly[[paste0("sd_gvi_", direction)]] <- vapply(
        gvi_results,
        function(x) x$directions[[direction]]$sd,
        numeric(1)
      )
    }
  }
  gvi_cols <- c("g_area", "mean_gvi", "bottom_gvi", "top_gvi",
                "bottom_green_area", "top_green_area", "mean_green_area")
  if (isTRUE(floor)) {
    gvi_cols <- c(gvi_cols, "estimated_floors", "min_gvi", "max_gvi", "sd_gvi")
  }
  if (!inherits(directions, "NULL")) {
    direction_cols <- unlist(lapply(directions, function(direction) {
      paste0(c("gvi_bottom_", "gvi_top_", "mean_gvi_", "min_gvi_", "max_gvi_", "sd_gvi_"), direction)
    }))
    gvi_cols <- c(gvi_cols, direction_cols)
  }
  projected_poly <- copy_group_results(projected_poly, analysis_poly, gvi_cols)
  # cli::cli_alert_success('Finished calculating GVIs')

  end_time <- Sys.time()
  process_time <- as.numeric(difftime(end_time, start_time, units = "secs"))
  if (!quiet) time_taken(process_time)

  return(projected_poly)
}

#' Visualize an Individual Building BGVI Viewshed
#'
#' Computes and optionally plots the BGVI viewshed for one building and one
#' viewpoint height. The function uses the same DSM, green feature layer, target
#' footprint flattening, and flat-roof handling as [get_bgvi()], but returns the
#' diagnostic layers for a single building instead of summary columns for every
#' building.
#'
#' @param x sf. Building footprint polygons, typically output from
#'   [search_3dglobdf()]. Must include a `Height` column.
#' @param building Integer row number, or a value from the `id` column when `id`
#'   is present.
#' @param level Character. One of `"bottom"` or `"top"`. Ignored when `floor`
#'   or `height` is supplied.
#' @param floor Integer floor number to visualize. Floor 1 is 1.7 m above
#'   ground; higher floors add 3 m each.
#' @param height Numeric observer offset above ground in metres. Overrides
#'   `level` and `floor` when supplied.
#' @param orientation Optional sector orientation. Supply a bearing in degrees
#'   clockwise from north, or one of `"north"`, `"northeast"`, `"east"`,
#'   `"southeast"`, `"south"`, `"southwest"`, `"west"`, or `"northwest"`.
#'   If `NULL`, the full viewshed is used.
#' @param field_of_view Numeric angular width in degrees for `orientation`.
#' @param datasource_canopy_height,datasource_greenspace,min_tree_height,zoom,radius,year,resolution,key,quiet
#'   Passed to the BGVI raster preparation workflow; see [get_bgvi()].
#' @param plot Logical. If `TRUE`, draw the viewshed map.
#' @param scalebar Logical. If `TRUE`, add a scale bar using the package's
#'   shared map layout.
#' @param scalebar_unit Character. Unit for the scale bar: `"auto"`, `"km"`,
#'   or `"m"`.
#' @param scalebar_cex Numeric text size for the scale bar and north arrow.
#' @param north_arrow Logical. If `TRUE`, add a north arrow.
#' @param ... Additional arguments passed to the initial viewshed `plot()`.
#'
#' @return A list containing the selected `building`, `viewpoint`, observer
#'   `height`, `gvi`, `green_area`, `viewshed`, `viewshed_raster`,
#'   `viewshed_area`, `radius`, `visible_green`, `sector_mask`, `plot_raster`,
#'   `dsm`, and `binary_green`.
#'
#' @examples
#' \donttest{
#' result <- plot_bgvi_viewshed(
#'   globfp_example,
#'   building = 1,
#'   level = "top",
#'   orientation = "south",
#'   field_of_view = 60,
#'   datasource_canopy_height = "metachm",
#'   key = "YOUR_opentopography_API_KEY"
#' )
#' }
#'
#' @export
plot_bgvi_viewshed <- function(x,
                               building = 1,
                               level = c("bottom", "top"),
                               floor = NULL,
                               height = NULL,
                               orientation = NULL,
                               field_of_view = 45,
                               datasource_canopy_height = "metachm",
                               datasource_greenspace = NULL,
                               min_tree_height = 2,
                               zoom = 17,
                               radius = 800,
                               year = NULL,
                               resolution = NULL,
                               key = NULL,
                               plot = TRUE,
                               scalebar = TRUE,
                               scalebar_unit = c("auto", "km", "m"),
                               scalebar_cex = 0.7,
                               north_arrow = TRUE,
                               quiet = FALSE,
                               ...) {
  if (inherits(x, "NULL")) {
    if (!quiet) cli::cli_alert_info("Please input building footprint polygon generated by `search_3dglobdf()`.")
    return(x)
  }
  if (!inherits(x, "sf")) {
    stop("`x` must be an sf building footprint object.", call. = FALSE)
  }
  if (!"Height" %in% names(x)) {
    stop("`x` must include a `Height` column.", call. = FALSE)
  }
  extra_args <- list(...)
  if ("datasource" %in% names(extra_args)) {
    stop("`datasource` is no longer supported by `plot_bgvi_viewshed()`; use `datasource_canopy_height` and `datasource_greenspace`.", call. = FALSE)
  }
  if (inherits(key, "NULL")) {
    stop("API key for OpenTopography is missing.")
  }
  field_of_view <- validate_bgvi_field_of_view(field_of_view)
  level <- match.arg(level)

  original_timeout <- getOption("timeout")
  on.exit(options(timeout = original_timeout), add = TRUE)
  options(timeout = 9999)

  old_terra_progress <- terra::terraOptions(print = FALSE)$progress
  terra::terraOptions(progress = 0)
  on.exit(terra::terraOptions(progress = old_terra_progress), add = TRUE)

  bgvi_inputs <- prepare_bgvi_inputs(
    x = x,
    datasource_canopy_height = datasource_canopy_height,
    datasource_greenspace = datasource_greenspace,
    min_tree_height = min_tree_height,
    zoom = zoom,
    radius = radius,
    year = year,
    resolution = resolution,
    key = key,
    quiet = quiet
  )

  analysis_poly <- bgvi_inputs$analysis_poly
  building_index <- resolve_bgvi_building_index(analysis_poly, building)
  target_building <- analysis_poly[building_index, ]
  scene <- prepare_bgvi_building_scene(
    building = target_building,
    dem = bgvi_inputs$dem,
    chm = bgvi_inputs$chm,
    binary_green = bgvi_inputs$binary_green,
    bh_all = bgvi_inputs$bh_all,
    base_elev = bgvi_inputs$base_elev,
    bldg_id = bgvi_inputs$bldg_id,
    radius = radius
  )

  observer_height <- resolve_bgvi_observer_height(
    building = target_building,
    level = level,
    floor = floor,
    height = height
  )

  if (!requireNamespace("viewscape", quietly = TRUE)) {
    stop("Package 'viewscape' is required for this function. Install it with: install.packages('viewscape')", call. = FALSE)
  }
  viewshed <- viewscape::compute_viewshed(
    dsm = scene$dsm,
    viewpoints = scene$viewpoint,
    offset_viewpoint = observer_height,
    r = radius
  )

  feature <- scene$binary_green
  sector_mask <- bgvi_sector_mask(feature, scene$viewpoint, orientation, field_of_view)
  if (!inherits(orientation, "NULL")) {
    center <- bgvi_orientation_to_bearing(orientation)
    feature <- directional_green_feature_bearing(feature, scene$viewpoint, center, field_of_view)
  }
  gvi <- gvi_from_viewshed(viewshed, target_building, feature)
  viewshed_raster <- align_bgvi_viewshed_raster(viewshed_to_spatraster(viewshed), feature)
  visible_green <- terra::ifel(viewshed_raster > 0 & feature == 1, 1, NA)
  plot_raster <- bgvi_plot_raster(
    list(
      viewshed_raster = viewshed_raster,
      sector_mask = sector_mask,
      binary_green = scene$binary_green,
      visible_green = visible_green,
      building = target_building,
      orientation = orientation,
      viewpoint = scene$viewpoint,
      radius = radius
    ),
    buildings = bgvi_inputs$projected_poly
  )

  result <- list(
    building = target_building,
    viewpoint = scene$viewpoint,
    height = observer_height,
    level = if (is.null(height) && is.null(floor)) level else NULL,
    floor = floor,
    orientation = orientation,
    field_of_view = if (is.null(orientation)) NULL else field_of_view,
    radius = radius,
    gvi = as.numeric(gvi$gvi),
    green_area = as.numeric(gvi$green_area),
    viewshed_area = as.numeric(gvi$viewshed_area),
    viewshed = viewshed,
    viewshed_raster = viewshed_raster,
    visible_green = visible_green,
    sector_mask = sector_mask,
    plot_raster = plot_raster,
    dsm = scene$dsm,
    binary_green = scene$binary_green
  )

  if (isTRUE(plot)) {
    plot_bgvi_viewshed_result(
      result,
      buildings = bgvi_inputs$projected_poly,
      scalebar = scalebar,
      scalebar_unit = scalebar_unit,
      scalebar_cex = scalebar_cex,
      north_arrow = north_arrow,
      ...
    )
    return(invisible(result))
  }
  result
}

#' @description
#' `get_dng`: Calculate the distance to the nearest greenspace (DNG) patch
#' for each building volume
#' @param datasource character. (only required for `get_bgvi` and `get_dng`)
#'   Green/canopy data source. Supported values are `"metachm"`, `"esri"`, and
#'   `"sentinel2"` for `get_dng`.
#' @param min_area numeric. (only required for `get_dng`) The minimum area
#' (the unit is defined by `unit`) of greenspace patches within the proximity of
#' a building.
#' For example, when `min_area = 500`, any greenspace patches with area less than
#' 500 square meter will be excluded.
#' @param unit character. (only required for `get_dng`) The unit for
#' `min_area`: 'm2','ha', and 'km2'.
#' @param network `NULL`, character, or `sf`. (only required for `get_dng`)
#' Controls whether distances are measured along a real street network instead
#' of in a straight line. Use `NULL` (the default) for straight-line distance,
#' `"osm"` to download a walkable OpenStreetMap network for the study extent,
#' or supply your own `sf` line layer of road/path centre lines. When routing
#' is requested, the distance is the sum of the walk from the building centroid
#' to the network, the shortest path along the network, and the walk from the
#' network to the green-space pixel.
#' @param overpass_url character. (only required for `get_dng` when
#' `network = "osm"`) Overpass API endpoint used to download the street
#' network.
#' @param timeout numeric. (only required for `get_dng` when `network = "osm"`)
#' Overpass query timeout in seconds. Default is 180.
#' @param workers integer. (only required for `get_dng`) Number of parallel
#' workers for per-building distance computation. Defaults to one fewer than
#' available cores. Use \code{workers = 1} to run sequentially.
#'
#' @return
#' `get_dng` returns an `sf` object identical to input \code{x},
#' with additional columns:
#' \code{dng}: Distance to nearest green space (tree canopy pixel) in meters,
#' measured along the street network when `network` is supplied; and
#' \code{dng_method}: either \code{"network"} or \code{"euclidean"}, recording
#' how each value was obtained. Buildings that cannot reach any green space
#' through the network fall back to straight-line distance and are flagged
#' \code{"euclidean"}.
#'
#' @examples
#' result <- gloBFPr::get_dng(#globfp_example[c(1:3),],
#'                            datasource = "metachm",
#'                            unit = "m2")
#'
#' # Measure along real road and path centre lines instead
#' result <- gloBFPr::get_dng(#globfp_example[c(1:3),],
#'                            datasource = "metachm",
#'                            unit = "m2",
#'                            network = "osm")
#' @export
#' @rdname get_metrics

get_dng <- function(x = NULL,
                     datasource = NULL,
                     min_tree_height = 2,
                     zoom = 17,
                     radius = 800,
                     min_area = 500,
                     unit = c('m2','ha','km2'),
                     year = NULL,
                     network = NULL,
                     overpass_url = "https://overpass-api.de/api/interpreter",
                     timeout = 180,
                     workers = NULL,
                     quiet = FALSE) {
  if (inherits(x, 'NULL')) {
    if (!quiet) cli::cli_alert_info("Please input building footprint polygon.")
    return(x)
  }

  unit <- match.arg(unit)
  if (inherits(datasource, 'NULL')) {
    stop("Please input datasource: 'metachm', 'esri', or 'sentinel2'.")
  }
  datasource <- match.arg(datasource, c("metachm", "esri", "sentinel2"))

  old_opt <- getOption("future.globals.maxSize")
  on.exit(options(future.globals.maxSize = old_opt), add = TRUE)
  options(future.globals.maxSize = 3 * 1024^3)

  if (inherits(workers, "NULL")) {
    workers <- max(1, as.numeric(future::availableCores()) - 1)
  } else {
    workers <- as.integer(workers[1])
    if (is.na(workers) || workers < 1L) workers <- 1L
  }
  os <- Sys.info()[["sysname"]]
  if (workers == 1) {
    future::plan(future::sequential)
  } else if (os == "Windows" || isFALSE(parallelly::supportsMulticore())) {
    future::plan(future::multisession, workers = workers)
  } else {
    future::plan(future::multicore, workers = workers)
  }
  on.exit(future::plan(future::sequential), add = TRUE)

  bbox <- get_bbox(x)
  utm_crs <- get_utm_crs(bbox)
  projected_poly <- sf::st_transform(x, utm_crs)
  analysis_poly <- prepare_group_analysis_buildings(projected_poly)
  analysis_poly$dng <- NA_real_
  analysis_poly$dng_method <- NA_character_

  # Download greenspace once for the full study extent (padded by radius),
  # filter patches globally, then extract all green pixel coordinates once.
  analysis_bbox <- get_bbox(sf::st_buffer(projected_poly, dist = radius))
  if (!quiet) cli::cli_alert_info('Downloading greenspace data ...')
  gs_full <- get_greenspace(analysis_bbox, NULL, datasource, zoom, year, min_tree_height)
  gs_full <- filter_patch_area(gs_full, min_area, unit = unit, directions = 8)
  green_points_all <- terra::as.points(terra::ifel(gs_full == 1, 1, NA), na.rm = TRUE)
  green_xy_all <- if (nrow(green_points_all) > 0) terra::crds(green_points_all) else matrix(numeric(0), ncol = 2)
  rm(gs_full, green_points_all)

  # Pre-compute all building centroids in UTM.
  centroids_all <- sf::st_coordinates(
    suppressWarnings(sf::st_centroid(analysis_poly))
  )[, 1:2, drop = FALSE]

  # Download/prepare the routing graph once for the whole study extent.
  graph_obj <- resolve_dng_network(
    network = network,
    extent = sf::st_buffer(sf::st_as_sfc(sf::st_bbox(projected_poly)), radius),
    utm_crs = utm_crs,
    overpass_url = overpass_url,
    timeout = timeout,
    quiet = quiet
  )

  if (is.null(graph_obj)) {
    # --- Fast euclidean path: single C++ call for all buildings ---
    if (nrow(green_xy_all) == 0) {
      analysis_poly$dng <- NA_real_
      analysis_poly$dng_method <- NA_character_
    } else {
      analysis_poly$dng <- nearest_green_cpp(centroids_all, green_xy_all, radius)
      analysis_poly$dng_method <- ifelse(is.na(analysis_poly$dng), NA_character_, "euclidean")
    }
  } else {
    # --- Network routing path: parallelize per-building ---
    gs_path <- tempfile(fileext = ".tif")
    gs_write <- get_greenspace(analysis_bbox, NULL, datasource, zoom, year, min_tree_height)
    gs_write <- filter_patch_area(gs_write, min_area, unit = unit, directions = 8)
    terra::writeRaster(gs_write, gs_path, overwrite = TRUE)
    on.exit(unlink(gs_path), add = TRUE)
    rm(gs_write)

    building_list <- lapply(seq_len(nrow(analysis_poly)), function(i) {
      list(poly = analysis_poly[i, ])
    })

    dng_results <- furrr::future_map(
      building_list,
      function(b) {
        gs <- terra::rast(gs_path)
        poly_ <- b$poly$geometry
        buffer_ <- get_buffer(x = poly_, radius = radius)
        buf_vect <- terra::vect(buffer_$buffer)
        gs_crop <- terra::mask(terra::crop(gs, terra::ext(buf_vect)), buf_vect)
        green_points <- terra::as.points(terra::ifel(gs_crop == 1, 1, NA), na.rm = TRUE)
        if (nrow(green_points) == 0) return(list(dng = NA_real_, method = NA_character_))

        green_xy <- terra::crds(green_points)
        centroid_xy <- sf::st_coordinates(buffer_$centroid)[1, 1:2, drop = FALSE]
        local_crs <- sf::st_crs(buffer_$centroid)
        routed <- network_distance_to_targets(
          graph_obj,
          to_graph_crs(centroid_xy, local_crs, graph_obj),
          to_graph_crs(green_xy, local_crs, graph_obj)
        )

        if (is.finite(routed$distance)) {
          list(dng = routed$distance, method = "network")
        } else {
          euclid <- sqrt(
            (green_xy[, 1] - centroid_xy[1, 1])^2 +
              (green_xy[, 2] - centroid_xy[1, 2])^2
          )
          list(dng = min(euclid), method = "euclidean")
        }
      },
      .options = furrr::furrr_options(seed = TRUE),
      .progress = !quiet
    )

    analysis_poly$dng <- vapply(dng_results, function(r) r$dng, numeric(1))
    analysis_poly$dng_method <- vapply(dng_results, function(r) r$method, character(1))
  }

  if (!is.null(graph_obj) && !quiet) {
    n_fallback <- sum(analysis_poly$dng_method == "euclidean", na.rm = TRUE)
    if (n_fallback > 0) {
      cli::cli_alert_warning(
        paste0(n_fallback, " unit(s) could not be routed; straight-line distance used.")
      )
    }
  }

  projected_poly <- copy_group_results(projected_poly, analysis_poly,
                                       c("dng", "dng_method"))
  return(projected_poly)
}
