# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

allocate_population_cpp <- function(pop_total, cell_group, volume, area) {
    .Call(`_gloBFPr_allocate_population_cpp`, pop_total, cell_group, volume, area)
}

mean_pairwise_distance <- function(coords) {
    .Call(`_gloBFPr_mean_pairwise_distance`, coords)
}

nearest_green_cpp <- function(centroids, green_xy, radius) {
    .Call(`_gloBFPr_nearest_green_cpp`, centroids, green_xy, radius)
}

building_shadow_height_cpp <- function(xy, rings, ring_building, ring_part, ring_is_hole, heights, dx_unit, dy_unit, tan_elev) {
    .Call(`_gloBFPr_building_shadow_height_cpp`, xy, rings, ring_building, ring_part, ring_is_hole, heights, dx_unit, dy_unit, tan_elev)
}

canopy_shadow_height_cpp <- function(xy, canopy_xy, canopy_height, canopy_ground, target_ground, dx_unit, dy_unit, tan_elev, half_cell) {
    .Call(`_gloBFPr_canopy_shadow_height_cpp`, xy, canopy_xy, canopy_height, canopy_ground, target_ground, dx_unit, dy_unit, tan_elev, half_cell)
}

svf_cpp <- function(xy, azimuth, rings, ring_building, building_height, building_ground, canopy_xy, canopy_height, canopy_ground, observer_ground, observer_height, canopy_cell_size, max_distance) {
    .Call(`_gloBFPr_svf_cpp`, xy, azimuth, rings, ring_building, building_height, building_ground, canopy_xy, canopy_height, canopy_ground, observer_ground, observer_height, canopy_cell_size, max_distance)
}

